"""Plumbing shared by the three generated scripts.

Each of ``bin/compile-emails``, ``bin/check-emails`` and
``bin/preview-emails`` is generated by :mod:`imio.recipe.emailkit` as

    sys.exit(imio.recipe.emailkit.<module>.main(config={...}))

``config`` carries the part's resolved options. Every option is also
overridable on the command line.
"""

from imio.recipe.emailkit import projects as projects_module

import argparse
import logging
import sys


#: Defaults for every key in ``config``, so a script with no config still works.
DEFAULTS = {
    "kit_mode": "path",
    "kit_dir": None,
    "node_bin": "node",
    "part": "emails",
}


def configure_logging(verbose=False):
    """Plain progress messages on stdout; failure summaries go to stderr."""
    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.INFO,
        format="%(message)s",
        stream=sys.stdout,
    )


def base_parser(prog, description):
    parser = argparse.ArgumentParser(prog=prog, description=description)
    parser.add_argument(
        "--package",
        metavar="NAME",
        default=None,
        help=(
            "act on this package only, as named by its <emailkit:templates> "
            "ZCML registration. Default: every registered package."
        ),
    )
    parser.add_argument(
        "--kit-mode",
        choices=("path", "copy"),
        default=None,
        help="override the part's kit-mode for this run.",
    )
    parser.add_argument(
        "--kit-dir",
        metavar="DIR",
        default=None,
        help="override the resolved design-kit directory. For tests.",
    )
    parser.add_argument(
        "--node-bin",
        metavar="PATH",
        default=None,
        help="the `node` executable to use; `npm` and `npx` are taken beside it.",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="print what was discovered and exit, without running anything.",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    return parser


def settings(config, arguments):
    """Merge ``DEFAULTS`` < the part's ``config`` < the command line."""
    merged = dict(DEFAULTS)
    merged.update(
        {key: value for key, value in (config or {}).items() if value is not None}
    )
    for key in ("kit_mode", "kit_dir", "node_bin"):
        value = getattr(arguments, key, None)
        if value is not None:
            merged[key] = value
    return merged


def discover(arguments, merged):
    """``(projects, kit_dir)`` for this run, or raise :class:`ProjectError`.

    Discovered now, since a develop checkout can change between runs.
    """
    found = projects_module.select(
        projects_module.from_environment(), arguments.package
    )
    kit_dir = merged.get("kit_dir")
    if not kit_dir:
        kit_dir = projects_module.kit_dir_from_environment()
    return found, kit_dir


def print_discovery(found, kit_dir, merged, stream=None):
    stream = stream or sys.stdout
    print(f"design kit : {kit_dir}  (kit-mode = {merged['kit_mode']})", file=stream)
    print(f"packages   : {len(found)}", file=stream)
    for project in found:
        print(f"  {project.package}", file=stream)
        print(f"      templates : {project.templates_dir}", file=stream)
        print(
            f"      emails    : "
            f"{project.emails_dir or '(not shipped, so not compilable)'}",
            file=stream,
        )
        if project.compilable:
            authored = sorted(project.sources_dir.rglob("*.vue"))
            print(
                f"      sources   : {len(authored)} .vue in {project.sources_dir}",
                file=stream,
            )
        if project.kit_dir is not None:
            kit_sources = sorted(project.kit_dir.rglob("*.vue"))
            print(
                f"      kit       : {len(kit_sources)} .vue in {project.kit_dir} "
                "(this package ships the design system)",
                file=stream,
            )


def nothing_to_do(found, what):
    """Report packages that ship no sources, and say whether any work remains."""
    compilable = [project for project in found if project.compilable]
    for project in found:
        if not project.compilable:
            print(
                f"  skip      {project.package}: ships no `emails/` directory, so "
                f"there is nothing to {what}. That is normal for an installed egg "
                f"(it is pruned from the sdist).",
            )
    return compilable


def report_error(exc):
    """One line on stderr, no traceback. These are user errors, not crashes."""
    sys.stdout.flush()
    print(f"error: {exc}", file=sys.stderr)
    return 1
