"""Wire the built-in design kit into a consumer's Maizzle project.

``bin/compile-emails`` resolves the kit directory from the installed
``imio.emailkit`` egg and wires it into each consumer's Maizzle build -- either by
pointing the Maizzle components/layouts paths at the egg directory directly, or by
materializing a copy into the consumer's ``emails/.kit/`` (gitignored) before
building. The recipe owns this choice; consumers never vendor kit files.

**Both modes materialise ``emails/.kit/``, and that is the point.** A consumer's
``maizzle.config.js`` always writes the same three lines:

    import { defineConfig } from '@maizzle/framework'
    import { kitBaseConfig } from './.kit/maizzle.config.base.js'
    export default defineConfig({ ...kitBaseConfig(), output: { ... } })

In ``path`` mode ``.kit/`` holds a two-line re-export of the real files inside the
egg, so ``kitBaseConfig()`` still derives ``kitDir`` from the *egg's* location and
Maizzle reads components straight out of ``site-packages`` -- genuine zero-copy. In
``copy`` mode ``.kit/`` holds the real thing. The consumer's config cannot tell,
and does not have to.

Nothing here runs Node. Wiring is file copying and two generated text files.
"""

from pathlib import Path

import json
import logging
import shutil


logger = logging.getLogger("imio.recipe.emailkit")

#: ``emails/.kit/`` -- gitignored, materialized by the recipe.
KIT_DIRNAME = ".kit"

#: The file a consumer's Maizzle config imports, in either mode.
BASE_CONFIG = "maizzle.config.base.js"

#: The kit's Tailwind entry: a CSS entry, not a JS preset.
CSS_ENTRY = "tailwind.css"

#: Written next to the wiring so `check-emails` and a puzzled human can both see
#: what mode produced what.
STAMP = "kit.json"

MODES = ("path", "copy")

#: Self-ignoring, so the recipe never edits a consumer's ``.gitignore``.
GITIGNORE = "# Generated by imio.recipe.emailkit. Not source; never commit it.\n*\n"


class KitError(Exception):
    """The kit could not be wired into a project."""


def wire(project, kit_dir, mode="path"):
    """Materialise ``emails/.kit/`` for ``project`` and return its path.

    Idempotent: safe to call before every build, which is what
    ``bin/compile-emails`` does, so a kit upgraded by a new egg release is picked
    up without anyone remembering to clean anything.
    """
    if mode not in MODES:
        raise KitError(f"kit-mode must be one of {' | '.join(MODES)}, not {mode!r}")
    if not project.compilable:
        raise KitError(
            f"{project.package} ships no Maizzle project, so there is nothing to "
            f"wire the kit into. `emails/` is pruned from the sdist, so "
            f"this is normal for an installed egg and means 'not compilable here'."
        )
    kit_dir = Path(kit_dir).resolve()
    if not kit_dir.is_dir():
        raise KitError(f"The kit directory {kit_dir} does not exist.")

    target = project.emails_dir / KIT_DIRNAME
    # Replaced wholesale rather than merged: a kit file deleted upstream must
    # disappear here too, and a `copy` -> `path` switch must not leave half a
    # copied kit behind for Maizzle to resolve components out of.
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)
    (target / ".gitignore").write_text(GITIGNORE, encoding="utf-8")

    if mode == "copy":
        _copy(kit_dir, target)
    else:
        _shim(kit_dir, target)

    (target / STAMP).write_text(
        json.dumps(
            {
                "mode": mode,
                "source": str(kit_dir),
                "package": project.package,
                "generated_by": "imio.recipe.emailkit",
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )
    logger.info("kit wired into %s (%s mode, from %s)", target, mode, kit_dir)
    return target


def _copy(kit_dir, target):
    """``copy`` mode: the kit's files, for real, inside the npm project."""
    for entry in sorted(kit_dir.iterdir()):
        if entry.name.startswith("."):
            continue
        destination = target / entry.name
        if entry.is_dir():
            shutil.copytree(entry, destination)
        else:
            shutil.copy2(entry, destination)


def _shim(kit_dir, target):
    """``path`` mode: two generated files that point at the egg.

    The JS shim re-exports rather than re-implements, so
    ``kitBaseConfig()``'s ``kitDir`` -- derived from ``import.meta.url`` of the
    *real* module -- stays the egg's kit directory. That is what makes
    ``components.source`` an absolute path outside the Maizzle project root, i.e.
    zero-copy mode, rather than a copy wearing its name.

    ``export *`` does not carry ``default``, hence the second pair of lines.
    """
    source = _js_string(kit_dir / BASE_CONFIG)
    (target / BASE_CONFIG).write_text(
        "// Generated by imio.recipe.emailkit (kit-mode = path). Do not edit.\n"
        "//\n"
        "// Re-exports the kit that ships inside the installed imio.emailkit egg,\n"
        "// so a consumer's maizzle.config.js imports './.kit/maizzle.config.base.js'\n"
        "// in either kit-mode and never vendors kit files.\n"
        f"export * from {source}\n"
        f"import kitDefaultConfig from {source}\n"
        "export default kitDefaultConfig\n",
        encoding="utf-8",
    )
    (target / CSS_ENTRY).write_text(
        "/*\n"
        " * Generated by imio.recipe.emailkit (kit-mode = path). Do not edit.\n"
        " *\n"
        " * The kit's locked, email-safe Tailwind entry, reached by absolute path\n"
        " * out of the installed egg. A consumer's own CSS entry imports this file.\n"
        " */\n"
        f"@import {_css_string(kit_dir / CSS_ENTRY)};\n",
        encoding="utf-8",
    )


def _js_string(path):
    """``path`` as a JS/JSON string literal, escaping included."""
    return json.dumps(str(path))


def _css_string(path):
    return json.dumps(str(path))


def read_stamp(project):
    """The wiring stamp of ``project``, or ``None`` when it has never been wired."""
    if not project.compilable:
        return None
    stamp = project.emails_dir / KIT_DIRNAME / STAMP
    if not stamp.is_file():
        return None
    try:
        return json.loads(stamp.read_text(encoding="utf-8"))
    except ValueError:
        return None
