<script setup>
/**
 * `KitButton` -- the bulletproof call to action.
 *
 * A single-cell table holding a BLOCK anchor that carries the padding, which is
 * what the v2 mockups draw and what makes the whole coloured rectangle a click
 * target. The cell keeps `mso-padding-alt` with the same values, because Word's
 * renderer ignores padding on a block anchor and would otherwise draw a button
 * with the label flush against its edges.
 *
 * This is the one thing that changed from the pre-v2 button, and it is a bug
 * fix rather than a restyle: with the padding on the CELL and a bare inline
 * `<a>`, only the glyphs of the label were clickable. A recipient who aimed at
 * the coloured area around the text hit nothing at all.
 *
 * Two variants, both from the v2 design:
 *
 *   solid    (default) filled with `primary_color`, white label. One per mail.
 *   outline  a 2 px `#b3004b` rule and a `#b3004b` label on no fill, for the
 *            second action in the rare mail that has two ("review" / "send
 *            back"). Not a fill, so that the pair reads as one primary action
 *            with an alternative rather than as two equal choices.
 *
 * `inline` drops the component's own top margin, for the buttons
 * `KitButtonGroup` puts on one row the way the mockup's notification model does.
 * The button stays a table there, nested inside the group's cell: a table in a
 * `<td>` is the most portable construct in mail, and it keeps this file's output
 * identical in both positions apart from that one margin.
 *
 * `variant` is resolved at BUILD time, so the class strings are literal in the
 * compiled output; a runtime-computed class is SPEC §3 rule 2 and would style
 * nothing.
 *
 * The `primary_color` theme token rides on `bgcolor`, not on `style`. A
 * Chameleon placeholder in a literal `style` attribute silently kills CSS
 * inlining for the whole document; `bgcolor` is never parsed as CSS, and it is
 * also the most widely supported way to colour a cell in mail. It is emitted
 * only for the solid variant -- an outline button has no fill, and `bgcolor` on
 * a transparent cell would fill it.
 *
 * `primary_color` is defined by the shell (`layouts/Main.vue`), so this component
 * only works inside it, which is the only place it is meant to be used.
 *
 * ---------------------------------------------------------------------------
 * The corner radius, and Outlook
 * ---------------------------------------------------------------------------
 * 12 px, matching the card and the callouts. Outlook on Windows renders the
 * button SQUARE, and that is the one place this component knowingly departs from
 * the v2 mockups, which give Outlook a VML `<v:roundrect>` instead.
 *
 * `<v:roundrect>` needs the button's WIDTH in pixels. The mockups can hardcode
 * one because each is a single fixed sentence of French; this component cannot,
 * because the label is a translated slot whose length changes per language, and
 * a `width` prop the author measured by hand would be wrong in at least two of
 * the three languages this package ships. Ghost padding (`mso-text-raise` and a
 * spacer `<i>`) sizes a fluid button in Outlook without a width, but it sizes it
 * only -- the corners stay square either way, so it would buy nothing here that
 * `mso-padding-alt` does not already buy more simply.
 *
 * So: rounded wherever `border-radius` works, square in Outlook, and correct
 * padding, colour and click target in both.
 *
 * Import-free: a kit directory inside a Python egg has no `node_modules`
 * ancestor. `defineProps` is a compiler macro, not an import.
 */
const props = defineProps({
  /** Destination. A Chameleon placeholder is fine here -- `href` is not CSS. */
  href: { type: String, required: true },
  /** Horizontal placement of the button block: `left`, `center` or `right`. */
  align: { type: String, default: 'left' },
  /** `solid` (default) or `outline`. */
  variant: { type: String, default: 'solid' },
  /** Drop the outer top margin, for `KitButtonGroup`. See the header note. */
  inline: { type: Boolean, default: false },
})

const isOutline = props.variant === 'outline'

/**
 * Whole utility names on both sides of the choice, never assembled from
 * fragments: Tailwind's content scanner reads this file, and a name that only
 * exists after a concatenation is generated by nothing.
 *
 * `mso-padding-alt` repeats the anchor's padding for Word's renderer, which
 * applies neither padding nor `display: block` to an `<a>`. Without it the
 * Outlook button is the label with a coloured border one pixel from the glyphs.
 * The outline variant's values are 2 px smaller on each axis, because its own
 * 2 px rule makes up the difference.
 */
const cellClass = isOutline
  ? 'rounded-[12px] border-2 border-solid border-imio-magenta-dark text-center [mso-padding-alt:11px_24px]'
  : 'rounded-[12px] text-center [mso-padding-alt:13px_26px]'

/**
 * The padding lives here, on a block anchor, so the whole rectangle is a link.
 * `rounded-[10px]` inside the outline variant's 12 px cell: a border radius is
 * measured on the OUTSIDE of the border, so an inner box that wants to sit flush
 * against a 2 px rule has to be 2 px tighter or its corners cut the rule.
 */
const labelClass = isOutline
  ? 'block rounded-[10px] px-6 py-[11px] text-base font-bold leading-tight text-imio-magenta-dark no-underline'
  : 'block rounded-[12px] px-[26px] py-[13px] text-base font-bold leading-tight text-imio-white no-underline'
</script>

<template>
  <table role="presentation" :align="align" :class="inline ? '' : 'mt-5'">
    <tr>
      <td v-if="isOutline" :class="cellClass">
        <a :href="href" :class="labelClass"><slot /></a>
      </td>
      <td v-else bgcolor="${primary_color}" :class="cellClass">
        <a :href="href" :class="labelClass"><slot /></a>
      </td>
    </tr>
  </table>
</template>
