<script setup>
/**
 * `KitDataRow` -- one label/value pair inside a `KitDataList`.
 *
 *     <KitDataList>
 *       <KitDataRow>
 *         <template #label><span i18n:translate="email_field_author" tal:omit-tag="">Author</span></template>
 *         ${author}
 *       </KitDataRow>
 *     </KitDataList>
 *
 * The two cells the v2 mockups draw: a fixed 130 px label column in
 * `#3c3c3b`, and a bold `#1c1c1c` value that takes the rest. Before this
 * component an author copied about ninety characters of utility classes per
 * cell, twice a row, and the shipped template with a single row quietly proved
 * how easy it was to get the separator wrong -- it had none at all.
 *
 * ---------------------------------------------------------------------------
 * The separator is NOT here
 * ---------------------------------------------------------------------------
 * The rule between rows is a `tr + tr > td` selector in `kit/tailwind.css`,
 * scoped to `KitDataList`'s own class, and it draws a border on the TOP of every
 * row but the first. That inversion is the whole point: a bottom border has to
 * be left off the LAST row, which nothing in an email can express -- CSS
 * inlining flattens the document long before `:last-child` could apply, and a
 * `last` prop would make the author's markup order load-bearing. A top border
 * skips the first row instead, and "first" is something a sibling combinator
 * knows without being told.
 *
 * ---------------------------------------------------------------------------
 * Why this one may be a component when the rows of `KitDataTable` may not
 * ---------------------------------------------------------------------------
 * `tal:` is kept off kit components, because Vue's attribute
 * fallthrough puts it on whichever element happens to be the root -- so a
 * repeated row has to be the author's own `<tr>`. A `KitDataList` is a fixed
 * handful of facts, never a repeat: that is the line between it and
 * `KitDataTable` (see `DataList.vue`). Nothing here is repeated, so nothing here
 * needs `tal:repeat`, and the component is safe. A list that does need one keeps
 * writing its own `<tr>`, which still works -- this component adds a shorthand,
 * it does not close the door.
 *
 * Import-free, like every kit component.
 */
defineProps({
  /**
   * Width of the label column in pixels, `'130'` (the mockups' value for the
   * account and error models) or `'120'` (the notification model's).
   *
   * A STRING, so that `label-width="120"` works as written. An email template is
   * markup all the way down and an author writing a number there would get a
   * Vue prop-type warning and a silently unstyled column; `:label-width="120"`
   * is the shape that avoids it, and asking for a binding on a constant is the
   * kind of detail that gets copied wrong. Emitted as the `width` ATTRIBUTE as
   * well as a class, because Outlook sizes a column from the attribute and
   * ignores the CSS.
   */
  labelWidth: { type: String, default: '130' },
})
</script>

<template>
  <tr>
    <!-- `w-[130px]` and `w-[120px]` written out whole rather than built from the
         prop: Tailwind's scanner reads this file as text, and a class name that
         only exists after an interpolation is generated by nothing. -->
    <td
      :width="labelWidth"
      :class="[
        labelWidth === '120' ? 'w-[120px]' : 'w-[130px]',
        'px-[14px] py-[10px] text-[13px] leading-5 text-imio-grey-dark',
      ]"
    >
      <slot name="label" />
    </td>
    <td class="px-[14px] py-[10px] text-[13px] font-bold leading-5 text-imio-black">
      <slot />
    </td>
  </tr>
</template>
