<script setup>
/**
 * `KitDataRow` renders one label/value pair inside a `KitDataList`: a
 * fixed-width label column, and a bold value that takes the rest.
 *
 * Prop: `labelWidth` (string, default `'130'`). Slots: `label`, default
 * (value).
 *
 * Mail-client traps
 * ------------------
 * - The separator between rows is a `tr + tr > td` rule in
 *   `kit/tailwind.css`: a top border on every row but the first, since a
 *   bottom border on every row but the last cannot be expressed
 *   (`:last-child` does not survive CSS inlining).
 * - `labelWidth` is a string, not a number, so `label-width="120"` works
 *   as written; a number gives a Vue prop-type warning and a silently
 *   unstyled column. Emitted as the `width` ATTRIBUTE as well as a class,
 *   since Outlook sizes a column from the attribute and ignores the CSS.
 */
defineProps({
  labelWidth: { type: String, default: '130' },
})
</script>

<template>
  <tr>
    <!-- Written out whole, not built from the prop: a class name from
         interpolation is generated by nothing for Tailwind's scanner. -->
    <td
      :width="labelWidth"
      :class="[
        labelWidth === '120' ? 'w-[120px]' : 'w-[130px]',
        'px-[14px] py-[10px] text-[13px] leading-5 text-imio-grey-dark',
      ]"
    >
      <slot name="label" />
    </td>
    <td class="px-[14px] py-[10px] text-[13px] font-bold leading-5 text-imio-black">
      <slot />
    </td>
  </tr>
</template>
