/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// Generated by Maizzle for prefixed component sources

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    KitButton: typeof import('../../src/imio/emailkit/kit/components/Button.vue')['default']
    KitDataTable: typeof import('../../src/imio/emailkit/kit/components/DataTable.vue')['default']
    KitMain: typeof import('../../src/imio/emailkit/kit/layouts/Main.vue')['default']
    KitPanel: typeof import('../../src/imio/emailkit/kit/components/Panel.vue')['default']
  }
}
